export const FETCH_STUDENTS = "FETCH_STUDENTS";
export const RECEIVE_STUDENTS = "RECEIVE_STUDENTS";
export const FETCH_WORDS = "FETCH_WORDS";
export const RECEIVE_WORDS = "RECEIVE_WORDS";
export const FETCH_STUDENT_WORDS = "FETCH_STUDENT_WORDS";
export const RECEIVE_STUDENT_WORDS = "RECEIVE_STUDENT_WORDS";
export const ADD_STUDENT = "ADD_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const FETCH_STUDENT = "FETCH_STUDENT";
export const RECEIVE_STUDENT = "RECEIVE_STUDENT";
export const FETCH_WORD = "FETCH_WORD";
export const ADD_WORD = "ADD_WORD";
export const RECEIVE_WORD = "RECEIVE_WORD";
export const DELETE_WORD = "DELETE_WORD";
export const WORD_ERROR = "WORD_ERROR";
export const FETCH_UNKNOWN_WORDS = "FETCH_UNKNOWN_WORDS";
export const RECEIVE_UNKNOWN_WORDS = "RECEIVE_UNKNOWN_WORDS";
export const ADD_STUDENT_WORDS = "ADD_STUDENT_WORDS";
export const FETCH_STUDENT_WORD_TEST_RESULTS =
  "FETCH_STUDENT_WORD_TEST_RESULTS";
export const RECEIVE_STUDENT_WORD_TEST_RESULTS =
  "RECEIVE_STUDENT_WORD_TEST_RESULTS";
export const ADD_WORD_TEST = "ADD_WORD_TEST";
export const SET_USER = "SET_USER";
export const CHECK_USER = "CHECK_USER";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOGOUT_USER = "LOGOUT_USER";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_ERROR = "REGISTER_ERROR ";
export const FETCH_LETTER = "FETCH_LETTER";
export const ADD_LETTER = "ADD_LETTEr";
export const RECEIVE_LETTER = "RECEIVE_LETTER";
export const DELETE_LETTER = "DELETE_LETTER";
export const LETTER_ERROR = "LETTER_ERROR";
export const FETCH_LETTERS = "FETCH_LETTERS";
export const RECEIVE_LETTERS = "RECEIVE_LETTERS";
export const FETCH_STUDENT_LETTERS = "FETCH_STUDENT_LETTERS";
export const RECEIVE_STUDENT_LETTERS = "RECEIVE_STUDENT_LETTERS";
export const FETCH_UNKNOWN_LETTERS = "FETCH_UNKNOWN_LETTERS";
export const RECEIVE_UNKNOWN_LETTERS = "RECEIVE_UNKNOWN_LETTERS";
export const ADD_STUDENT_LETTERS = "ADD_STUDENT_LETTERS";
export const RECEIVE_STUDENT_LETTER_TEST_RESULTS =
  "RECEIVE_STUDENT_LETTER_TEST_RESULTS";
export const ADD_LETTER_TEST = "ADD_LETTER_TEST";
export const FETCH_STUDENT_LETTER_TEST_RESULTS =
  "FETCH_STUDENT_LETTER_TEST_RESULTS";
export const FETCH_SOUND = "FETCH_SOUND";
export const ADD_SOUND = "ADD_SOUND";
export const RECEIVE_SOUND = "RECEIVE_SOUND";
export const DELETE_SOUND = "DELETE_SOUND";
export const SOUND_ERROR = "SOUND_ERROR";
export const FETCH_SOUNDS = "FETCH_SOUNDS";
export const RECEIVE_SOUNDS = "RECEIVE_SOUNDS";
export const FETCH_STUDENT_SOUNDS = "FETCH_STUDENT_SOUNDS";
export const RECEIVE_STUDENT_SOUNDS = "RECEIVE_STUDENT_SOUNDS";
export const FETCH_UNKNOWN_SOUNDS = "FETCH_UNKNOWN_SOUNDS";
export const RECEIVE_UNKNOWN_SOUNDS = "RECEIVE_UNKNOWN_SOUNDS";
export const ADD_STUDENT_SOUNDS = "ADD_STUDENT_SOUNDS";
export const RECEIVE_STUDENT_SOUND_TEST_RESULTS =
  "RECEIVE_STUDENT_SOUND_TEST_RESULTS";
export const ADD_SOUND_TEST = "ADD_SOUND_TEST";
export const FETCH_STUDENT_SOUND_TEST_RESULTS =
  "FETCH_STUDENT_SOUND_TEST_RESULTS";
